version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pawel
      - POSTGRES_PASSWORD=fliga
      - POSTGRES_DB=leaguedatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: